[package]
name = "kessler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "kessler"
crate-type = ["cdylib"]

[dependencies]
blas-src = { version = "0.8", features = ["openblas"] }
ndarray = { version = "0.14.0", features = ["blas", "rayon"] }
ndarray-linalg = "0.13"
ndarray-rand = "0.13.0"
openblas-src = { version = "0.10", features = ["cblas", "system"] }
rand = "0.8.5"
rand_distr = "0.4.3"
